[package]
name = "helpbutton"
version = "0.1.0"
authors = ["MelonRed"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysfs_gpio = "0.5.4"
twilio = "1.0.0"
futures = "0.3"
tokio = { features = ["full"] }